typography_spectrum: 0.713859
color:
  brandColors:
    - '#E7E7EA'
    - '#010203'
    - '#BBBCAC'
    - '#534B5B'
    - '#6591A4'
  brandStrength: 0.0625
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5298685
analytics:
  google: UA-73056752-1
  facebook: null
  twitter: null
name: k o l Ã© w a j u
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: blog
    url: 'http://kolewaju.com/'
    type: external
  - name: about
    id: daa5fe5f-ad1a-46e9-aca2-30b5bba9db40
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: build forth
purpose: []
